### ISSUE TITLE
ModuleNotFoundError: No module named 'mcp'

### ISSUE THREAD

**Issue by mcarreraf** [langchain-ai/langchain-mcp-adapters#54]
Hello guys!

I was trying to follow the quick start with the only change of instead of using openai for the model I use groq, the problem is that when I use the `uv run_client.py` command I get an error with the module but I already have it installed with uv.

```python
 ~#@❯ uv run client.py --verbose
Traceback (most recent call last):
  File "C:\Users\fmus\Documents\Repos\mcp_test\langchain-mcp-adapters\math_server.py", line 2, in <module>
    from mcp.server.fastmcp import FastMCP
ModuleNotFoundError: No module named 'mcp'
```

This is the connect of my pyproject.toml file

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "langchain-mcp-adapters"
version = "0.0.5"
description = "Make Anthropic Model Context Protocol (MCP) tools compatible with LangChain and LangGraph agents."
authors = [
    { name = "Vadym Barda", email = "19161700+vbarda@users.noreply.github.com" },
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-core>=0.3.36,<0.4",
    "langchain-groq>=0.2.4",
    "langchain-ollama>=0.2.3",
    "langgraph>=0.3.21",
    "mcp[cli]>=1.4.1,<1.5",
    "ollama>=0.4.7",
]

[dependency-groups]
test = [
    "pytest>=8.0.0",
    "ruff>=0.9.4",
    "mypy>=1.8.0",
    "pytest-socket>=0.7.0",
    "pytest-asyncio>=0.25.0",
    "types-setuptools>=69.0.0",
]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q -v"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "B", # flake8-bugbear
]
ignore = [
    "E501", # line-length
]


[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

```

I would appreciate it if someone can put me on the right track,  since Im probably missing something about the execution or installation of packages.
